[programs.localnet]
topdev = "CK6CX3Pk6K6rYDMqZPifsL279QisiqNh2SLLyAXShFEb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dragon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
